### ISSUE TITLE
Set up our Kanban board (https://github.com/ElsonOtake/TVMaze/)

### ISSUE THREAD

**Issue by ElsonOtake** [ElsonOtake/TVMaze#21]
There are two people in our team:

- Andres Garzon Maldonado;
- Elson Akio Otake

This is our link to the [project Kanban board](https://github.com/ElsonOtake/TVMaze/projects/2)

**Comment by t-yanick** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a link to the project Kanban board in the issue summary. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by danmainah** [comment]
Hi @ElsonOtake and @andgarzonmal , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Good design
✔️ Good Description

# Required Changes ♻️
Kindly ensure all cards are assigned to team members and are fairly assigned.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by andgarzonmal** [comment]
Hello, thanks for your review  

There are two people in our team:

- Andres Garzon Maldonado;
- Elson Akio Otake

This is our link to the [project Kanban board](https://github.com/ElsonOtake/TVMaze/projects/2)

**Comment by OmarRamoun** [comment]
# 🟢 Project Approved! 🏆

## Hi @ElsonOtake and @andgarzonmal 👋

Your project is complete! ✔️ 🏁

Congratulations! 🎉. 

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@omarramoun](https://img.shields.io/github/followers/omarramoun?label=Ramoun&style=social)](https://github.com/omarramoun)
- This is My **Twitter**: [![@omarramoun](https://img.shields.io/twitter/follow/omarramoun?label=ramoun16&style=social)](https://twitter.com/omarramoun)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
